### ISSUE TITLE
Stopped working without any apparent errors in debug logs

### ISSUE THREAD

**Issue by ikornaselur** [gabe565/CastSponsorSkip#71]
I noticed that skipping sponsor segments stopped working in the past week or two, but the logs are really not showing any activity.

Restarting the players and the container didn't seem to fix the issue. 

I'm running CSS in docker with the following docker-compose:

```yaml
version: "3.9"

services:
  app:
    image: ghcr.io/gabe565/castsponsorskip:latest
    environment:
      TZ: UTC
      CSS_YOUTUBE_API_KEY: ${API_KEY}
      CSS_LOG_LEVEL: debug
    network_mode: host
    restart: unless-stopped
```

and the logs just show "Requesting update":

```
time=2024-02-15T19:09:27.556Z level=INFO msg="CastSponsorSkip v0.7.2 (efdb2b5)"
time=2024-02-15T19:09:27.556Z level=INFO msg="Searching for devices..."
time=2024-02-15T19:09:27.762Z level=INFO msg="Connected to cast device." device=Shield
time=2024-02-15T19:09:27.776Z level=DEBUG msg="Ignoring device." device="Speaker" reason="Does not support video"
time=2024-02-15T19:09:27.785Z level=INFO msg="Connected to cast device." device="Kitchen Display"
time=2024-02-15T19:09:28.263Z level=DEBUG msg="Requesting update." device=Shield
time=2024-02-15T19:09:28.287Z level=DEBUG msg="Requesting update." device="Kitchen Display"
time=2024-02-15T19:09:40.290Z level=DEBUG msg="Requesting update." device=Shield
```

---

I was initially running CSS in a k3s cluster, where it had been running version 5.0.0 for a long time without issues, but tried updating to 0.7.2 there and then migrating to a separate server with just Docker directly.

Any thoughts on how I could troubleshoot further? For reference, the main player I use is a Nvidia Shield (not the pro)
